import { mkdir, readFile, writeFile, unlink, access } from 'node:fs/promises'
import { dirname, join, resolve, sep } from 'node:path'
import type { StorageService } from './index'

/**
 * Local disk storage. Development only.
 *
 * Production uses R2 — see the note in index.ts. This exists so the whole
 * application can be built and tested without any cloud credentials.
 */
export class LocalStorage implements StorageService {
  private readonly root: string

  constructor(root: string) {
    this.root = resolve(root)
  }

  /**
   * Resolve a key to a path and refuse anything that escapes the root.
   * Keys are generated by storageKey() and never contain user input, but a
   * traversal guard costs nothing and the day someone adds a shortcut it is
   * the only thing standing between a filename and /etc/passwd.
   */
  private pathFor(key: string): string {
    const full = resolve(join(this.root, key))
    if (full !== this.root && !full.startsWith(this.root + sep)) {
      throw new Error(`Storage key escapes the root: ${key}`)
    }
    return full
  }

  async put(key: string, body: Buffer, _contentType: string): Promise<void> {
    const path = this.pathFor(key)
    await mkdir(dirname(path), { recursive: true })
    await writeFile(path, body)
  }

  async get(key: string): Promise<Buffer> {
    return readFile(this.pathFor(key))
  }

  async delete(key: string): Promise<void> {
    try {
      await unlink(this.pathFor(key))
    } catch (err) {
      // Deleting something already gone is success, not failure.
      if ((err as NodeJS.ErrnoException).code !== 'ENOENT') throw err
    }
  }

  async exists(key: string): Promise<boolean> {
    try {
      await access(this.pathFor(key))
      return true
    } catch {
      return false
    }
  }
}
